language: python
python:
- 3.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: pablete
  password:
    secure: mgQC/bZan5FBeHVrk7YY0axBADqxFjYnlwussb1Y6OKhSedl3V1zJjWGEaT4AoqXY/LSet6fs5GspTNxT3xMlFsNS1/3da6u8eeQwNNxbvz74E++beO4Y8mCWbrD0w298cZCttQJdUsSkbJgjl45rTts/zihkyDZwJ+0/fr0RhSbPSdqL9eVZ43XP8sCxcHcR5BOD/dooGkfXtR+58Fl20gaLCp4nnZ2GHniWh0HEf/feXvmB9rVw4mZWLLzCcr/Rnv9dKRLgShsK/z16tNUKYVDF5uEGMmMSq/g6Ng4f8BdcrkScTATDn/Xgz1CRV4FQ+oeiWBFqDtSnfAov+R0WdUnbHV3c9Hc4DSY7mxf6IG5rS2yMZcPw+aVcQcunQhTvBWAZaRAYIU0MY1elXIrH7GpG4MCDzrobNlrWjWcPP+McIVY3X59a47oyAtmPaKuDtzLTPiY026IR3HFz1Fov8RjkajaVOuGPMLq4kuvoxUp8LiwUFjeIVk4EPl8L/KMU68ZigXJFQ2F2vbWIm8xnVrVNwoP00/lTy/Eda5T/zEqgcBo54hctkb7Rg+dMvuj6hTrRaCR0dS1wAi9YF6rzpaAv1JKyZwnnr0iWr0H+H1ZSJjWJ5a16d+qlkFqlqFL0gBZ5FwyvNcMplD3kznq0rhZEbsw5dYEkHOF15p5lwU=
  on:
    tags: true
    repo: pablete/frameworker
    python: 3.7
